### ISSUE TITLE
Outdated script version

### ISSUE THREAD

**Issue by rafamanzo** [travisjeffery/sinon-rails#9]
First of all, thanks for producing this gem. This is by far the most downloaded gem on rubygems.org that provides Sinon.JS.

But it is by far outdated (1.10.3 vs 1.15.0) and may lead many developers that intend to test JS on their applications to use this old version.

I created this issue in order you first of all if there is any known issue that is blocking update before creating my own fork and releasing it on rubygems. I see there are enough PRs and forks with this purpose, but none merged so that's why of my question.

Thank you once more for your time.

**Comment by travisjeffery** [comment]
just updated to the latest version, thanks!
